ESWProjectAlbergue/Models/PerfectAnimal.cs
// ***********************************************************************
// Assembly         : ESWProjectAlbergue
// Author           : migue
// Created          : 02-08-2019
//
// Last Modified By : migue
// Last Modified On : 02-08-2019
// ***********************************************************************
// <copyright file="PerfectAnimal.cs" company="ESWProjectAlbergue">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ESWProjectAlbergue.Models
{
    /// <summary>
    /// Class PerfectAnimal.
    /// </summary>
    public class PerfectAnimal
    {

        /// <summary>
        /// Gets or sets the perfect animal identifier.
        /// </summary>
        /// <value>The perfect animal identifier.</value>
        public int PerfectAnimalId { get; set; }

        /// <summary>
        /// Gets or sets the type.
        /// </summary>
        /// <value>The type.</value>
        [Display(Name = "Tipo de Animal")]
        public EnumAnimalType Type { get; set; }

        /// <summary>
        /// Gets or sets the gender.
        /// </summary>
        /// <value>The gender.</value>
        [Display(Name = "Género")]
        public EnumGenderType Gender { get; set; }

        /// <summary>
        /// Gets or sets the breed identifier.
        /// </summary>
        /// <value>The breed identifier.</value>
        [Display(Name = "Raça")]
        public int BreedId { get; set; }

        /// <summary>
        /// Gets or sets the breed.
        /// </summary>
        /// <value>The breed.</value>
        [Display(Name = "Raça")]
        public AnimalBreed Breed { get; set; }

        /// <summary>
        /// Gets or sets the size.
        /// </summary>
        /// <value>The size.</value>
        [Display(Name = "Tamanho")]
        public EnumSize Size { get; set; }

        /// <summary>
        /// Gets or sets the age.
        /// </summary>
        /// <value>The age.</value>
        [Display(Name = "Idade")]
        public EnumAgeType Age { get; set; }

        /// <summary>
        /// Gets or sets the animal identifier.
        /// </summary>
        /// <value>The animal identifier.</value>
        [Display(Name = "Animal Adotado")]
        public int AnimalId { get; set; }

        /// <summary>
        /// Gets or sets the animal.
        /// </summary>
        /// <value>The animal.</value>
        public Animal Animal { get; set; }

        /// <summary>
        /// Gets or sets the percentagem.
        /// </summary>
        /// <value>The percentagem.</value>
        public int Percentagem { get; set; }
    }
}

ESWProjectAlbergue/Controllers/PerfectAnimalsController.cs
// ***********************************************************************
// Assembly         : ESWProjectAlbergue
// Author           : migue
// Created          : 02-08-2019
//
// Last Modified By : migue
// Last Modified On : 02-08-2019
// ***********************************************************************
// <copyright file="PerfectAnimalsController.cs" company="ESWProjectAlbergue">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ESWProjectAlbergue.Models;

namespace ESWProjectAlbergue.Controllers
{
    /// <summary>
    /// Class PerfectAnimalsController.
    /// Implements the <see cref="Microsoft.AspNetCore.Mvc.Controller" />
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    public class PerfectAnimalsController : Controller
    {
        /// <summary>
        /// The context
        /// </summary>
        private readonly ESWProjectAlbergueContext _context;

        /// <summary>
        /// Initializes a new instance of the <see cref="PerfectAnimalsController"/> class.
        /// </summary>
        /// <param name="context">The context.</param>
        public PerfectAnimalsController(ESWProjectAlbergueContext context)
        {
            _context = context;
        }

        // GET: PerfectAnimals
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Index()
        {
            var eSWProjectAlbergueContext = _context.PerfectAnimal.Include(p => p.Breed);
            ViewData["BreedId"] = new SelectList(_context.AnimalBreed, "Id", "Name");
            return View(nameof(Create));
        }

        // GET: PerfectAnimals/Details/5
        /// <summary>
        /// Detailses the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var perfectAnimal = await _context.PerfectAnimal
                .Include(p => p.Breed)
                .FirstOrDefaultAsync(m => m.PerfectAnimalId == id);
            if (perfectAnimal == null)
            {
                return NotFound();
            }

            return View(perfectAnimal);
        }

        // GET: PerfectAnimals/Create
        /// <summary>
        /// Creates this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Create()
        {
            ViewData["BreedId"] = new SelectList(_context.AnimalBreed, "Id", "Name");
            return View();
        }

        // POST: PerfectAnimals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.


        // GET: PerfectAnimals/Edit/5
        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var perfectAnimal = await _context.PerfectAnimal.FindAsync(id);
            if (perfectAnimal == null)
            {
                return NotFound();
            }
            ViewData["BreedId"] = new SelectList(_context.AnimalBreed, "Id", "Name", perfectAnimal.BreedId);
            return View(perfectAnimal);
        }

        // POST: PerfectAnimals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="perfectAnimal">The perfect animal.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PerfectAnimalId,Size,Gender,BreedId,Age,Type")] PerfectAnimal perfectAnimal)
        {
            if (id != perfectAnimal.PerfectAnimalId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(perfectAnimal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PerfectAnimalExists(perfectAnimal.PerfectAnimalId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BreedId"] = new SelectList(_context.AnimalBreed, "Id", "Name", perfectAnimal.BreedId);
            return View(perfectAnimal);
        }

        // GET: PerfectAnimals/Delete/5
        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var perfectAnimal = await _context.PerfectAnimal
                .Include(p => p.Breed)
                .FirstOrDefaultAsync(m => m.PerfectAnimalId == id);
            if (perfectAnimal == null)
            {
                return NotFound();
            }

            return View(perfectAnimal);
        }

        // POST: PerfectAnimals/Delete/5
        /// <summary>
        /// Deletes the confirmed.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var perfectAnimal = await _context.PerfectAnimal.FindAsync(id);
            _context.PerfectAnimal.Remove(perfectAnimal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Perfects the animal exists.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns><c>true</c> if XXXX, <c>false</c> otherwise.</returns>
        private bool PerfectAnimalExists(int id)
        {
            return _context.PerfectAnimal.Any(e => e.PerfectAnimalId == id);
        }


        /// <summary>
        /// Filtrar os animais de acordo com as caracteristicas procuradas pelo utilizador
        /// </summary>
        /// <param name="perfectAnimal">The perfect animal.</param>
        /// <returns>Um view com o animal  que for 100% o que o ulizador procura ou varios ordenados pelas percentagens de compatibilidade</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GetAnimalIdeal([Bind("PerfectAnimalId,Size,Gender,BreedId,Age,Type")] PerfectAnimal perfectAnimal)
        {
            var percentagem = 0;
            List<PerfectAnimal> animal = new List<PerfectAnimal>();
            var animaisideais = from a in _context.Animal select a;
            var animalIdeal = from a in _context.Animal where a.AnimalType == perfectAnimal.Type && a.Gender == perfectAnimal.Gender && a.AgeType == perfectAnimal.Age && a.BreedId == perfectAnimal.BreedId &&  a.SizeType == perfectAnimal.Size select a;
            if(animalIdeal.Count() >= 1)
            {
                foreach (var item in animalIdeal)
                { 
                    var pA = new PerfectAnimal { Animal = item };
                    pA.Percentagem = 100;
                    animal.Add(pA);
                }
                return View(animal);
            }
            var animaistipo = from a in _context.Animal where a.AnimalType == perfectAnimal.Type && a.Adopted == false select a;

            if (animaistipo.Count() == 0)
            {
                return NotFound();
            }
            if (animaistipo.Count() >= 1)
            {
                foreach (var item in animaistipo)
                {        
                    animal.Add(HowPerfect(new PerfectAnimal(), item));
                }
                
            }
            
            ViewData["BreedId"] = new SelectList(_context.AnimalBreed, "Id", "Name", perfectAnimal.BreedId);
            animal.Sort((x, y) => x.Percentagem.CompareTo(y.Percentagem));
            animal.Reverse();
            return View(animal);
        }

        /// <summary>
        /// Analisa os animais consoante as caracteristicas do utilizadpr
        /// </summary>
        /// <param name="perfectAnimal">The perfect animal.</param>
        /// <param name="animal">The animal.</param>
        /// <returns>O animal com a sua percentagem de compatibilidade</returns>
        public PerfectAnimal HowPerfect(PerfectAnimal perfectAnimal, Animal animal)
        {
            var count = 0;

            if(perfectAnimal.Type == animal.AnimalType)
            {
                count += 20;
            }

ESWProjectAlbergue/Views/PerfectAnimals/Create.cshtml
@model ESWProjectAlbergue.Models.PerfectAnimal

@{
    ViewData["Title"] = "Create";
}


<link href="css/site.css" rel="stylesheet" type="text/css" />

<style>
    .container-all {
        background-color: #333333;
        padding: 20px;
        padding-top: 6px;
        border-style: solid;
        border-width: 5px;
        align-content: center;
        align-items: center;
        width: 100%;
        height: 100%;
        margin-top: 5px;
        margin-right: auto;
        margin-left: auto;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        display: inline-block;
        background-color: #333333;
        border-radius: 25px;
        position: center;
    }

    .whitetext {
        color: white;
        font-family: 'Quicksand', sans-serif;
        font-size: 16px;
    }

    .btn {
        background-color: white;
    }
    .registar-animal {
        font-family: "Pacifico";
        font-size: 40px;
        width: 100%;
        text-align: center;
        margin-top: 3%;
        color: #FFFFFF;
    }

    .form-create {
    }

    .creates {
        margin: 0 auto;
        width: fit-content;
    }

    .title {
        font-family: "Pacifico";
        font-size: 40px;
        width: 100%;
        text-align: center;
        color: #FFFFFF;
    }
</style> 


<div class="container-all">


    <div class="lembretestotal">
        <img src='~/images/paws.png' width="70" height="70" style="display: block; margin-left: auto; margin-right: auto;">
        <h2 class="title">Animal ideal</h2>

        <br>
        <div class="form-create">

            <div class="creates">

                <div class="helpregisterbox" style="text-align:center;">
                    <a class="btnhelpregister" href="#popup1" style="text-align:center;"> <img src="~/images/info.png" width="25" height="25" /> Ajuda</a>
                </div>
                <br>

                <div id="popup1" class="overlay">
                    <div class="popup" style="margin:0 auto; display:block;">
                        <h2 class="bold" style="text-align:center;">Ajuda- Animal Ideal</h2>
                        <a class="close" href="#">&times;</a>
                        <div class="content">

                            <p> Não sabe qual o animal ideal para si? Preencha o formulário com as características que gostaria num animal e descubra baseado na sua percentagem.</p>


                        </div>
                    </div>
                </div>




                <form asp-action="GetAnimalIdeal">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Type" class="control-label whitetext"></label>
                        <select asp-for="Type" class="form-control " style="font-size:13pt;width:300px;" asp-items="@Html.GetEnumSelectList<EnumAnimalType>()"></select>
                        <span asp-validation-for="Type" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Size" class="control-label whitetext"></label>
                        <select asp-for="Size" class="form-control" style="font-size:13pt;width:300px;" asp-items="@Html.GetEnumSelectList<EnumSize>()"></select>
                        <span asp-validation-for="Size" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Gender" class="control-label whitetext"></label>
                        <select asp-for="Gender" class="form-control" style="font-size:13pt;width:300px;" asp-items="@Html.GetEnumSelectList<EnumGenderType>()"></select>
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BreedId" class="control-label whitetext"></label>
                        <select asp-for="BreedId" class="form-control" style="font-size:13pt;width:300px;" asp-items="ViewBag.BreedId"></select>
                    </div>
                    <div class="form-group">
                        <label asp-for="Age" class="control-label whitetext"></label>
                        <select asp-for="Age" class="form-control" style="font-size:13pt;width:300px;" asp-items="@Html.GetEnumSelectList<EnumAgeType>()"></select>
                        <span asp-validation-for="Age" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Submeter" class="btn" />
                        <a asp-action="Index">Voltar</a>
                    </div>
                </form>
            </div>
        </div>



    </div>

ESWProjectAlbergue/Views/PerfectAnimals/Delete.cshtml
@model ESWProjectAlbergue.Models.PerfectAnimal

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PerfectAnimal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Breed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Breed.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PerfectAnimalId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ESWProjectAlbergue/Views/PerfectAnimals/Details.cshtml
@model ESWProjectAlbergue.Models.PerfectAnimal

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>PerfectAnimal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Breed)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Breed.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PerfectAnimalId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ESWProjectAlbergue/Views/PerfectAnimals/Edit.cshtml
@model ESWProjectAlbergue.Models.PerfectAnimal

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>PerfectAnimal</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PerfectAnimalId" />
            <div class="form-group">
                <label asp-for="Size" class="control-label"></label>
                <select asp-for="Size" class="form-control"></select>
                <span asp-validation-for="Size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select asp-for="Gender" class="form-control"></select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BreedId" class="control-label"></label>
                <select asp-for="BreedId" class="form-control" asp-items="ViewBag.BreedId"></select>
                <span asp-validation-for="BreedId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <select asp-for="Age" class="form-control"></select>
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <select asp-for="Type" class="form-control"></select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ESWProjectAlbergue/Views/PerfectAnimals/GetAnimalIdeal.cshtml
@model IEnumerable<ESWProjectAlbergue.Models.PerfectAnimal>

@{
    ViewData["Title"] = "Index";
    var imgsrc = "";
}


<!DOCTYPE html>

<head>
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

    <style>
        .animalscontainer {
            display: inline;
            width: auto;
            display: inline;
        }

        .animalcontainer {
            position: relative;
            width: auto;
            display: inline-block;
        }

        .animalimage {
            opacity: 1;
            display: block;
            width: 200px;
            height: 200px;
            transition: .5s ease;
            backface-visibility: hidden;
        }

        .middle {
            transition: .5s ease;
            opacity: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%)
        }

        .animalcontainer:hover .animalimage {
            opacity: 0.3;
        }

        .animalcontainer:hover .middle {
            opacity: 1;
        }

        .animalnamefemale {
            background-color: hotpink;
            color: white;
            font-size: 16px;
            padding: 16px 32px;
            border-radius: 100px;
            border-style: solid;
            border-width: 2px;
        }

        .animalnamemale {
            background-color: #02A69E;
            color: white;
            font-size: 16px;
            padding: 16px 32px;
            border-radius: 100px;
            border-style: solid;
            border-width: 2px;
        }

        .animalname {
            color: white;
            text-transform: uppercase;
        }



        a {
            color: black;
        }

        .editdelete {
            width: 200px;
        }

        .allanimals {
            background-color: #333333;
            padding: 20px;
            padding-top: 6px;
            border-style: solid;
            border-width: 5px;
            align-content: center;
            align-items: center;
            width: 100%;
            height: 100%;
            margin-top: 5px;
            margin-right: auto;
            margin-left: auto;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            display: inline-block;
            background-color: #333333;
            border-radius: 25px;
            position: center;
        }

        .Animais {
            font-family: "Pacifico";
            font-size: 40px;
            width: 100%;
            text-align: center;
            margin-top: 3%;
            color: #FFFFFF;
        }

        .whitetext {
            color: white;
            font-family: 'Open Sans', sans-serif;
        }

        .button1 {
            background-color: #02A69E;
            text-transform: uppercase;
            border: none;
            color: white;
            padding: 10px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 12px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 3px;
        }

            .button1:hover {
                background-color: gray;
                color: white;
            }

        .button2 {
            background-color: #02A69E;
            text-transform: uppercase;
            border: none;
            color: white;
            padding: 5px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 12px;
            margin: 4px 2px;
            margin-right: 20px;
            cursor: pointer;
            border-radius: 3px;
        }

            .button2:hover {
                background-color: gray;
                color: white;
            }

        .filteranimals {
            display: table;
            margin: 0 auto;
        }

        .filteranimalschildren {
            display: inline;
        }

        .centerdiv {
            display: table;
            margin: 0 auto;
        }

        .centerimage {
            display: block;
            margin-left: auto;
            margin-right: auto;
        }

        .centertext {
            text-align: center;
        }

        .divider {
            -webkit-filter: invert(100%);
            filter: invert(100%);
            width: 70%;
            display: block;
            margin-left: auto;
            margin-right: auto;
        }
    </style>
</head>
<body>
    <div class="allanimals">
        <h2 class="Animais">Animal Ideal</h2>
        <br>
        <h4 class="centertext whitetext">Lista dos animais ideais e a sua respetiva percentagem</h4>
        <br>


        <div class="filteranimals centerdiv">
            <form asp-controller="PerfectAnimals" asp-action="Index" method="post">
                <p>
                    <input type="submit" value="Voltar" />
                </p>
            </form>
        </div>


        <br>
        <div class="animalscontainer">
            @foreach (var item in Model)
            {

                @if (item.Animal.Photo == null)
                {
                    if (item.Animal.AnimalType == EnumAnimalType.CAT)
                    {
                        imgsrc = "~/images/caticon.png";
                    }
                    if (item.Animal.AnimalType == EnumAnimalType.DOG)
                    {
                        imgsrc = "~/images/dogicon.png";
                    }
                    if (item.Animal.AnimalType == EnumAnimalType.OTHER)
                    {
                        imgsrc = "~/images/interrogacao.png";
                    }

                }
                else
                {
                    var base64 = Convert.ToBase64String(item.Animal.Photo);
                    imgsrc = string.Format("data:image/gif;base64,{0}", base64);
                }


                @if (item.Animal.Gender == EnumGenderType.FEMALE)
                {
                    <div class="animalcontainer centerdiv">
                        <img src='@imgsrc' class="animalimage" width="200" height="200" style="border-radius:100px; border-style: solid; border-width: 5px; border-color: hotpink;" />
                        <div class="middle">
                            <div class="animalnamefemale">
                                @if (item.Animal.AnimalType == EnumAnimalType.CAT)
                                {
                                    <img src='~/images/cat.png' width="40" height="40" class="centerimage">

                                }
                                else
                                {
                                    <img src='~/images/dog.png' class="centerimage">
                                }

                                <a asp-controller="Animals" asp-action="Details" asp-route-id="@item.Animal.Id" class="animalname centertext">@Html.DisplayFor(model => item.Animal.Name)</a>
                            </div>
                        </div>
                    </div>

                }
                @if (item.Animal.Gender == EnumGenderType.MALE)
                {
                    <div class="animalcontainer centerdiv">
                        <img src='@imgsrc' class="animalimage" width="200px" height="200px" style="border-radius:100px; border-style: solid; border-width: 5px; border-color: #02A69E;" />
                        <div class="middle">
                            <div class="animalnamemale">
                                @if (item.Animal.AnimalType == EnumAnimalType.CAT)
                                {
                                    <img src='~/images/cat.png' width="40" height="40" class="centerimage">

                                }
                                else
                                {
                                    <img src='~/images/dog.png' class="centerimage">
                                }
                                <a asp-action="Details" asp-route-id="@item.Animal.Id" class="animalname">@Html.DisplayFor(model => item.Animal.Name)</a>
                            </div>
                        </div>
                    </div>
                }



                <p class="editdelete" style="color : white; margin-left:auto; margin-right:auto; text-align:center; font-size:20px; font-weight:bold; text-transform:capitalize;">

                    <br>
                    PERCENTAGEM=@item.Percentagem %  
                </p>
                <br>

                <img src="~/images/divider.png " class="divider" />
                <br>

            }
        </div>
    </div>

</body>