ESWProjectAlbergue/Models/AdoptionFile.cs
// ***********************************************************************
// Assembly         : ESWProjectAlbergue
// Author           : migue
// Created          : 02-07-2019
//
// Last Modified By : migue
// Last Modified On : 02-08-2019
// ***********************************************************************
// <copyright file="AdoptionFile.cs" company="ESWProjectAlbergue">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ESWProjectAlbergue.Models
{
    /// <summary>
    /// Class AdoptionFile.
    /// </summary>
    public class AdoptionFile
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>The identifier.</value>
        [Display(Name = "Nº de Ficha")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the animal identifier.
        /// </summary>
        /// <value>The animal identifier.</value>
        [Display(Name = "Animal Adotado")]
        public int AnimalId { get; set; }

        /// <summary>
        /// Gets or sets the animal.
        /// </summary>
        /// <value>The animal.</value>
        public Animal Animal { get; set; }

        /// <summary>
        /// Gets or sets the application user identifier.
        /// </summary>
        /// <value>The application user identifier.</value>
        [Display(Name = "Adotante")]
        public string ApplicationUserId { get; set; }

        /// <summary>
        /// Gets or sets the application user.
        /// </summary>
        /// <value>The application user.</value>
        public virtual ApplicationUser ApplicationUser { get; set; }

        /// <summary>
        /// Gets or sets the date.
        /// </summary>
        /// <value>The date.</value>
        [Display(Name = "Data de Adoção")]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }

        /// <summary>
        /// Gets or sets the status.
        /// </summary>
        /// <value>The status.</value>
        [Display(Name = "Estado do Pedido")]
        public EnumAdoptionStatus Status { get; set; }

        /// <summary>
        /// Gets or sets the order identifier.
        /// </summary>
        /// <value>The order identifier.</value>
        [Display(Name = "Formulário Pedido")]
        public int OrderId { get; set; }


    }
}

ESWProjectAlbergue/Controllers/AdoptionFilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ESWProjectAlbergue.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;

namespace ESWProjectAlbergue.Controllers
{
    /// <summary>
    /// Class AdoptionFilesController.
    /// Implements the <see cref="Microsoft.AspNetCore.Mvc.Controller" />
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    public class AdoptionFilesController : Controller
    {
        /// <summary>
        /// The context
        /// </summary>
        private readonly ESWProjectAlbergueContext _context;
        /// <summary>
        /// The user manager
        /// </summary>
        private readonly UserManager<ApplicationUser> _userManager;
        /// <summary>
        /// The email sender
        /// </summary>
        private readonly IEmailSender _emailSender;
      

        /// <summary>
        /// Initializes a new instance of the <see cref="AdoptionFilesController" /> class.
        /// </summary>
        /// <param name="context">The context.</param>
        /// <param name="userManager">The user manager.</param>
        /// <param name="emailSender">The email sender.</param>
        public AdoptionFilesController(ESWProjectAlbergueContext context, UserManager<ApplicationUser> userManager, IEmailSender emailSender)
        {
            _context = context;
            _userManager = userManager;
            _emailSender = emailSender;
        }

       

        // GET: AdoptionFiles
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Index()
        {
            var eSWProjectAlbergueContext = _context.AdoptionFile.Include(a => a.Animal).Include(u => u.ApplicationUser);
            ViewData["BreedId"] = new SelectList(_context.Set<AnimalBreed>(), "Id", "Name");
            return View(await eSWProjectAlbergueContext.ToListAsync());
        }

        // GET: AdoptionFiles/Details/5
        /// <summary>
        /// Detailses the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var adoptionFile = await _context.AdoptionFile
                .Include(a => a.Animal).Include(u => u.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (adoptionFile == null)
            {
                return NotFound();
            }

            return View(adoptionFile);
        }

        // GET: AdoptionFiles/Edit/5
        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var adoptionFile = await _context.AdoptionFile.FindAsync(id);
            if (adoptionFile == null)
            {
                return NotFound();
            }
            ViewData["AnimalId"] = adoptionFile.AnimalId;
            ViewData["AnimalName"] = _context.Animal.Find(adoptionFile.AnimalId).Name;
            ViewData["UserName"] = _context.User.Find(adoptionFile.ApplicationUserId).Name;
            return View(adoptionFile);
        }

        /// <summary>
        /// Edita do ficheiro de adoção e envia um email com as alterações
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="adoptionFile">The adoption file.</param>
        /// <returns>O ficheiro de adoção editado.</returns>
        // POST: AdoptionFiles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,AnimalId,ApplicationUserId,Status")] AdoptionFile adoptionFile)
        {
            if (id != adoptionFile.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if(adoptionFile.Status == EnumAdoptionStatus.ACEITE)
                    {
                        var animal = _context.Animal.Find(adoptionFile.AnimalId);
                        animal.Adopted= true;
                        _context.Update(animal);
                        await _context.SaveChangesAsync();
                    }
                    var user = await _userManager.FindByIdAsync(adoptionFile.ApplicationUserId);
                    await _emailSender.SendEmailAsync(user.Email, "Pedido de Adoção",
                   $"<h1> Pedido de Adoção </h1> " +
                   $"<h4> O seu pedido de adoção foi "+ adoptionFile.Status );

                    _context.Update(adoptionFile);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AdoptionFileExists(adoptionFile.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AnimalId"] = new SelectList(_context.Animal, "Id", "Id", adoptionFile.AnimalId);
            return View(adoptionFile);
        }

        // GET: AdoptionFiles/Delete/5
        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var adoptionFile = await _context.AdoptionFile
                .Include(a => a.Animal).Include(u=> u.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (adoptionFile == null)
            {
                return NotFound();
            }

            return View(adoptionFile);
        }

        // POST: AdoptionFiles/Delete/5
        /// <summary>
        /// Deletes the confirmed.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var adoptionFile = await _context.AdoptionFile.FindAsync(id);
            _context.AdoptionFile.Remove(adoptionFile);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Adoptions the file exists.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns><c>true</c> if XXXX, <c>false</c> otherwise.</returns>
        private bool AdoptionFileExists(int id)
        {
            return _context.AdoptionFile.Any(e => e.Id == id);
        }

        /// <summary>
        /// Filtrar as fichas de adoção pelas raças dos cães
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Um view com os animais da raça selecionada</returns>
        [HttpPost]
        public async Task<IActionResult> FiltrarRaca(int? id)
        {
            ViewData["BreedId"] = new SelectList(_context.Set<AnimalBreed>(), "Id", "Name");
            var breeds = await _context.AdoptionFile.Include(a => a.Animal).Include(u => u.ApplicationUser).ToListAsync();
            if (id != null)
            {
                var animais = await _context.Animal.ToListAsync();
                animais = (from a in animais where a.BreedId == id select a).ToList();
                breeds = (from a in breeds from u in animais where a.AnimalId == u.Id select a).ToList();

            }

            if (breeds == null)
            {
                return NotFound();
            }
            return View(breeds);

        }


        /// <summary>
        /// Filtrar as fichas de adoção pelas datas da adoção dos cães
        /// </summary>
        /// <param name="date">The date.</param>
        /// <returns>Um view com os animais adotados na data selecionada</returns>
        [HttpPost]
        public async Task<IActionResult> FiltrarDate(DateTime? date)
        {
            ViewData["BreedId"] = new SelectList(_context.Set<AnimalBreed>(), "Id", "Name");
            var breeds = await _context.AdoptionFile.Include(a => a.Animal).Include(u => u.ApplicationUser).ToListAsync();
            if (date != null) { 
            
                breeds = (from a in breeds where a.Date.Date == date select a).ToList();

            }

            if (breeds == null)
            {
                return NotFound();
            }
            return View(breeds);


        }
    }
}

ESWProjectAlbergue/Views/AdoptionFiles/Create.cshtml
@model ESWProjectAlbergue.Models.AdoptionFile

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>AdoptionFile</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AnimalId" class="control-label"></label>
                <select asp-for="AnimalId" class ="form-control" asp-items="ViewBag.AnimalId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationUserId" class="control-label"></label>
                <select asp-for="ApplicationUserId" class="form-control" asp-items="ViewBag.ApplicationUserId"></select>
                <span asp-validation-for="ApplicationUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ESWProjectAlbergue/Views/AdoptionFiles/Delete.cshtml
@model ESWProjectAlbergue.Models.AdoptionFile

@{
    ViewData["Title"] = "Delete";
}


<style>
    .container-all {
        background-color: #333333;
        padding: 20px;
        padding-top: 6px;
        border-style: solid;
        border-width: 5px;
        align-content: center;
        align-items: center;
        width: 100%;
        height: 100%;
        margin-top: 5px;
        margin-right: auto;
        margin-left: auto;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        display: inline-block;
        background-color: #333333;
        border-radius: 25px;
        position: center;
    }

    .whitetext {
        color: white;
        font-family: 'Quicksand', sans-serif;
        font-size: 16px;
    }

    .editar {
        font-family: "Pacifico";
        font-size: 40px;
        width: 100%;
        text-align: center;
        margin-top: 3%;
        color: #FFFFFF;
    }

    .form-create {
    }

    .creates {
        margin: 0 auto;
        width: fit-content;
    }

    .btnsalvar {
        background-color: #02A69E;
        text-transform: uppercase;
        border: none;
        color: white;
        padding: 10px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 10px;
    }

        .btnsalvar:hover {
            background-color: gray;
            color: white;
        }

    .btnatualizar {
        margin: 0 auto;
        align-content: center;
        display: table;
    }
</style>

<div class="container-all">

    <<div class="form-create">

        <div class="creates">
            <h2 class="editar">Eliminar Ficha de Adoção</h2>
            <br />



            <p class="whitetext">
                <span class="bold whitetext">
                    @Html.DisplayNameFor(model => model.Animal)
                </span>


                @Html.DisplayFor(model => model.Animal.Name)
            </p>

            <p class=" whitetext">
                <span class="bold whitetext">
                    Adotante
                </span>

                @Html.DisplayFor(model => model.ApplicationUser.Name)
            </p>

        </div>
        <div class="btnatualizar">
            <p class="bold whitetext">Tem a certeza que quer eliminar a ficha de adoção?</p>
            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Delete" class="btnsalvar" /> |
                <a asp-action="Index" class="btnsalvar">Voltar</a>
            </form>
        </div>
    </div>
</div>>

</div>

ESWProjectAlbergue/Views/AdoptionFiles/Details.cshtml
@model ESWProjectAlbergue.Models.AdoptionFile

@{
    ViewData["Title"] = "Details";
}
<style>
    .container-all {
        background-color: #333333;
        padding: 20px;
        padding-top: 6px;
        border-style: solid;
        border-width: 5px;
        align-content: center;
        align-items: center;
        width: 100%;
        height: 100%;
        margin-top: 5px;
        margin-right: auto;
        margin-left: auto;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        display: inline-block;
        background-color: #333333;
        border-radius: 25px;
        position: center;
    }

    .whitetext {
        color: white;
        font-family: 'Quicksand', sans-serif;
        font-size: 16px;
    }

    .editar {
        font-family: "Pacifico";
        font-size: 40px;
        width: 100%;
        text-align: center;
        margin-top: 3%;
        color: #FFFFFF;
    }

    .form-create {
    }

    .creates {
        margin: 0 auto;
        width: fit-content;
    }

    .btnsalvar {
        background-color: #02A69E;
        text-transform: uppercase;
        border: none;
        color: white;
        padding: 10px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
        cursor: pointer;
        border-radius: 10px;
    }

        .btnsalvar:hover {
            background-color: gray;
            color: white;
        }

    .btnatualizar {
        margin: 0 auto;
        align-content: center;
        display: table;
    }
</style>

<div class="container-all">

    <<div class="form-create">

         <div class="creates">
             <h2 class="editar">Detalhes Ficha Adoção</h2>
             <br />



             <p class="whitetext">
                 <span class="bold whitetext">
                     @Html.DisplayNameFor(model => model.Animal)
                 </span>


                 @Html.DisplayFor(model => model.Animal.Name)
                 </p>

             <p class=" whitetext">
                 <span class="bold whitetext">
                 Adotante
                 </span>

                 @Html.DisplayFor(model => model.ApplicationUser.Name)
             </p>

         </div>
        <div class="btnatualizar">
            <a asp-action="Edit" asp-route-id="@Model.Id" class="btnsalvar">Editar</a> |
            <a asp-action="Index" class="btnsalvar">Voltar</a>
        </div>
    </div>
</div>>

ESWProjectAlbergue/Views/AdoptionFiles/FiltrarDate.cshtml
@model IEnumerable<ESWProjectAlbergue.Models.AdoptionFile>

@{
    ViewData["Title"] = "FiltrarData";
}

<h2>FiltrarData</h2>

<form asp-controller="AdoptionFiles" asp-action="FiltrarRaca" method="post">
    <p>
        Raça: <select name="id" class="form-control" asp-items="ViewBag.BreedId"></select> <input type="submit" value="Filtrar" />

    </p>
</form>

<form asp-controller="AdoptionFiles" asp-action="FiltrarDate" method="post">
    <p>
        Data: <input type="date" name="date">
        <input type="submit" value="Filtrar" />
    </p>
</form>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Animal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationUser)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Animal.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicationUser.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

ESWProjectAlbergue/Views/AdoptionFiles/FiltrarRaca.cshtml
@model IEnumerable<ESWProjectAlbergue.Models.AdoptionFile>

@{
    ViewData["Title"] = "FiltrarRaca";
}

<h2>FiltrarRaca</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="AdoptionFiles" asp-action="FiltrarRaca" method="post">
    <p>
        Raça: <select name="id" class="form-control" asp-items="ViewBag.BreedId"></select>
        <input type="submit" value="Filtrar" />
    </p>
</form>

<form asp-controller="AdoptionFiles" asp-action="FiltrarDate" method="post">
    <p>
        Data: <input type="date" name="date">
        <input type="submit" value="Filtrar" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Animal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationUser)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Animal.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationUser.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

ESWProjectAlbergue/Views/AdoptionFiles/Index.cshtml
@model IEnumerable<ESWProjectAlbergue.Models.AdoptionFile>

@{
    ViewData["Title"] = "Index";
}



<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="vendor/perfect-scrollbar/perfect-scrollbar.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/css/csstable.css">
    <!--===============================================================================================-->
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">

    <style>
        .centerdiv {
            display: table;
            margin: 0 auto;
        }

        .whitetext {
            color: white;
            font-family: 'Open Sans', sans-serif;
        }

        .filteranimalschildren {
            display: inline;
        }

        .centertext {
            text-align: center;
        }

        .button1 {
            background-color: #02A69E;
            text-transform: uppercase;
            border: none;
            color: white;
            padding: 10px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 12px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 3px;
        }

            .button1:hover {
                background-color: gray;
                color: white;
            }

        .button2 {
            background-color: #02A69E;
            text-transform: uppercase;
            border: none;
            color: white;
            padding: 5px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 12px;
            margin: 4px 2px;
            margin-right: 20px;
            cursor: pointer;
            border-radius: 3px;
        }

            .button2:hover {
                background-color: gray;
                color: white;
            }

        .title {
            font-family: "Pacifico";
            font-size: 40px;
            width: 100%;
            text-align: center;
            color: #FFFFFF;
        }

        .color {
            background-color: #002439;
        }

    </style>

</head>
<body>
    <div class="lembretestotal">
        <img src='~/images/notes.png' width="60" height="60" style="display: block; margin-left: auto; margin-right: auto;">
        <h2 class="title">Fichas de adoção</h2>
        <br>



        <div class="filteranimals centerdiv">
            <form asp-controller="AdoptionFiles" asp-action="FiltrarRaca" method="post" class="whitetext filteranimalschildren">
                <p class="whitetext filteranimalschildren">
                    Raça: <select name="id" class="form-control" asp-items="ViewBag.BreedId"></select>
                    <input type="submit" class="button2" style="background-color:#F59A44;" value="Filtrar" />
                </p>
            </form>

            <form asp-controller="AdoptionFiles" asp-action="FiltrarDate" method="post" class="whitetext filteranimalschildren">
                <p class="whitetext filteranimalschildren">
                    Data: <input style="color:black" type="date" name="date">
                    <input type="submit" class="button2" style="background-color:#F59A44;" value="Filtrar" />
                </p>
            </form>
        </div>

        <div class="limiter">
            <div class="container-table100">
                <div class="wrap-table100">
                    <div class="table">

                        <div class="row header " style="background-color:	#F59A44;">
                            <div class="cell">
                                @Html.DisplayNameFor(model => model.Animal)
                            </div>
                            <div class="cell">
                                @Html.DisplayNameFor(model => model.ApplicationUser.Name)
                            </div>
                            <div class="cell">
                                @Html.DisplayNameFor(model => model.Date)
                            </div>
                            <div class="cell">
                                @Html.DisplayNameFor(model => model.Status)
                            </div>
                            <div class="cell">
                                @Html.DisplayNameFor(model => model.OrderId)
                            </div>
                            <div class="cell">
                                Ações
                            </div>
                        </div>

                        @foreach (var item in Model)
                        {
                            <div class="row">
                                <div class="cell" data-title="Full Name">
                                    @Html.DisplayFor(modelItem => item.Animal.Name)
                                </div>

                                <div class="cell" data-title="Full Name">
                                    @Html.DisplayFor(modelItem => item.ApplicationUser.Name)
                                </div>

                                <div class="cell" data-title="Full Name">
                                    @Html.DisplayFor(modelItem => item.Date)
                                </div>

                                <div class="cell" data-title="Full Name">
                                    @Html.DisplayFor(modelItem => item.Status)
                                </div>

                                <div class="cell" data-title="Full Name">
                                    <a asp-action="Edit" asp-route-id="@item.Id">Atualizar Estado</a>
                                </div>

                                <div class="cell" data-title="Full Name">

                                    <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                                    <a asp-action="Delete" asp-route-id="@item.Id">Eliminar</a>
                                </div>
                            </div>

                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
        <!--===============================================================================================-->
        <script src="vendor/jquery/jquery-3.2.1.min.js"></script>
        <!--===============================================================================================-->
        <script src="vendor/bootstrap/js/popper.js"></script>
        <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
        <!--===============================================================================================-->
        <script src="vendor/select2/select2.min.js"></script>
        <!--===============================================================================================-->
        <script src="js/main.js"></script>

</body>
</html>