ESWProjectAlbergue/Models/Animal.cs
// ***********************************************************************
// Assembly         : ESWProjectAlbergue
// Author           : migue
// Created          : 02-07-2019
//
// Last Modified By : migue
// Last Modified On : 01-22-2019
// ***********************************************************************
// <copyright file="Animal.cs" company="ESWProjectAlbergue">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ESWProjectAlbergue.Models
{
    /// <summary>
    /// Class Animal.
    /// </summary>
    public class Animal
    {
        /// <summary>
        /// Gets or sets the identifier.
        /// </summary>
        /// <value>The identifier.</value>
        [Display(Name = "Nº de Registo")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        /// <value>The name.</value>
        [Display(Name = "Nome")]
        [StringLength(40, ErrorMessage = "Nome não pode conter mais de 30 letras")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets the type of the animal.
        /// </summary>
        /// <value>The type of the animal.</value>
        [Display(Name = "Tipo de Animal")]
        public EnumAnimalType AnimalType { get; set; }

        /// <summary>
        /// Gets or sets the gender.
        /// </summary>
        /// <value>The gender.</value>
        [Display(Name = "Género")]
        public EnumGenderType Gender { get; set; }

        /// <summary>
        /// Gets or sets the birth date.
        /// </summary>
        /// <value>The birth date.</value>
        [Display(Name = "Data de Nascimento")]
        [DataType(DataType.Date)]
        public DateTime BirthDate { get; set; }

        /// <summary>
        /// Gets or sets the breed identifier.
        /// </summary>
        /// <value>The breed identifier.</value>
        [Display(Name = "Raça")]
        public int BreedId { get; set; }

        /// <summary>
        /// Gets or sets the breed.
        /// </summary>
        /// <value>The breed.</value>
        [Display(Name = "Raça")]
        public AnimalBreed Breed { get; set; }

        /// <summary>
        /// Gets or sets the type of the size.
        /// </summary>
        /// <value>The type of the size.</value>
        [Display(Name = "Tamanho")]
        public EnumSize SizeType { get; set; }

        /// <summary>
        /// Gets or sets the type of the fur.
        /// </summary>
        /// <value>The type of the fur.</value>
        [Display(Name = "Tipo de Pêlo")]
        public EnumFurType FurType  { get; set; }

        /// <summary>
        /// Gets or sets the type of the age.
        /// </summary>
        /// <value>The type of the age.</value>
        [Display(Name = "Idade")]
        public EnumAgeType AgeType { get; set; }

        /// <summary>
        /// Gets or sets the description.
        /// </summary>
        /// <value>The description.</value>
        [Display(Name = "Descrição")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets the type of the behavior.
        /// </summary>
        /// <value>The type of the behavior.</value>
        [Display(Name = "Comportamento")]
        public EnumBehaviorType BehaviorType { get; set; }

        /// <summary>
        /// Gets or sets the photo.
        /// </summary>
        /// <value>The photo.</value>
        [Display(Name = "Fotografia")]
        public byte[] Photo { get; set; }

        /// <summary>
        /// Gets or sets the adopted.
        /// </summary>
        /// <value>The adopted.</value>
        [Display(Name = "Adotado")]
        public Boolean Adopted { get; set; }



        


    }
}

ESWProjectAlbergue/Controllers/AnimalsController.cs
// ***********************************************************************
// Assembly         : ESWProjectAlbergue
// Author           : migue
// Created          : 01-21-2019
//
// Last Modified By : migue
// Last Modified On : 02-08-2019
// ***********************************************************************
// <copyright file="AnimalsController.cs" company="ESWProjectAlbergue">
//     Copyright (c) . All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ESWProjectAlbergue.Models;
using System.IO;
using System.Web;
using Microsoft.AspNetCore.Http;

namespace ESWProjectAlbergue.Controllers
{
    /// <summary>
    /// Class AnimalsController.
    /// Implements the <see cref="Microsoft.AspNetCore.Mvc.Controller" />
    /// </summary>
    /// <seealso cref="Microsoft.AspNetCore.Mvc.Controller" />
    public class AnimalsController : Controller
    {
        /// <summary>
        /// The context
        /// </summary>
        private readonly ESWProjectAlbergueContext _context;

        /// <summary>
        /// Initializes a new instance of the <see cref="AnimalsController"/> class.
        /// </summary>
        /// <param name="context">The context.</param>
        public AnimalsController(ESWProjectAlbergueContext context)
        {
            _context = context;
        }



        // GET: Animals
        /// <summary>
        /// Indexes this instance.
        /// </summary>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Index()
        {
            var eSWContext = _context.Animal.Include(c => c.Breed);
            return View(await eSWContext.ToListAsync());
        }



        // GET: Animals/Details/5
        /// <summary>
        /// Detailses the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animal
                .Include(c => c.Breed)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (animal == null)
            {
                return NotFound();
            }
            ViewData["BreedId"] = new SelectList(_context.Set<AnimalBreed>(), "Id", "Name", animal.BreedId);
            return View(animal);
        }

        // GET: Animals/Create
        /// <summary>
        /// Creates this instance.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Create()
        {
            ViewData["BreedId"] = new SelectList(_context.Set<AnimalBreed>(), "Id", "Name");
            
            return View();
        }

        // POST: Animals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Creates the specified animal.
        /// </summary>
        /// <param name="animal">The animal.</param>
        /// <param name="Photo">The photo.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,AnimalType,Gender,BirthDate,BreedId,SizeType,FurType,AgeType,Description,BehaviorType")] Animal animal,List<IFormFile> Photo)
        {
            ViewData["BreedId"] = new SelectList(_context.Set<AnimalBreed>(), "Id", "Name", animal.BreedId);
           
            foreach (var item in Photo) {
                if (item.Length > 0) {
                    using(var stream = new MemoryStream())
                    {
                        await item.CopyToAsync(stream);
                        animal.Photo = stream.ToArray();
                    }
                }
            }

            if (ModelState.IsValid)
            {
                _context.Add(animal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            TempData["Success"] = "<script>alert('Animal resgistado com sucesso');</script>";
            ModelState.Clear();
            return View(animal);
        }

        // GET: Animals/Edit/5
        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            ViewData["BreedId"] = new SelectList(_context.Set<AnimalBreed>(), "Id", "Name");
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animal.FindAsync(id);
            if (animal == null)
            {
                return NotFound();
            }
            ViewData["BreedId"] = new SelectList(_context.Set<AnimalBreed>(), "Id", "Name", animal.BreedId);
            return View(animal);
        }

        // POST: Animals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Edits the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <param name="animal">The animal.</param>
        /// <param name="Photo">The photo.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,AnimalType,Gender,BirthDate,BreedId,SizeType,FurType,AgeType,Description,BehaviorType,Adopted")] Animal animal, List<IFormFile> Photo)
        {
            ViewData["BreedId"] = new SelectList(_context.Set<AnimalBreed>(), "Id", "Name");
            if (id != animal.Id)
            {
                return NotFound();
            }

            foreach (var item in Photo)
            {
                if (item.Length > 0)
                {
                    using (var stream = new MemoryStream())
                    {
                        await item.CopyToAsync(stream);
                        animal.Photo = stream.ToArray();
                    }
                }
            } 
            if (ModelState.IsValid)
            {
                try
                {
                    ViewData["BreedId"] = new SelectList(_context.Set<AnimalBreed>(), "Id", "Name", animal.BreedId);
                   
                    _context.Update(animal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AnimalExists(animal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BreedId"] = new SelectList(_context.Set<AnimalBreed>(), "Id", "Name", animal.BreedId);
            return View(animal);
        }

        // GET: Animals/Delete/5
        /// <summary>
        /// Deletes the specified identifier.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var animal = await _context.Animal
                .FirstOrDefaultAsync(m => m.Id == id);
            if (animal == null)
            {
                return NotFound();
            }

            return View(animal);
        }

        // POST: Animals/Delete/5
        /// <summary>
        /// Deletes the confirmed.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Task&lt;IActionResult&gt;.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var animal = await _context.Animal.FindAsync(id);
            _context.Animal.Remove(animal);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Animals the exists.
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns><c>true</c> if XXXX, <c>false</c> otherwise.</returns>
        private bool AnimalExists(int id)
        {
            return _context.Animal.Any(e => e.Id == id);
        }

        /// <summary>
        /// Filtrar os animais pelo seu número de identificação
        /// </summary>
        /// <param name="id">The identifier.</param>
        /// <returns>Um view com o animal com o número de identificação selecionado</returns>
        [HttpPost]
        public async Task<IActionResult> FiltrarNumero(int? id)
        {
            var animais = await _context.Animal.ToListAsync();
            if (id != null)
            {
                animais = (from a in animais where a.Id == id select a).ToList();

            }

            if (animais == null)
            {
                return NotFound();
            }
            return View(animais);

        }

        /// <summary>
        /// Filtrars the nome.
        /// </summary>

ESWProjectAlbergue/Views/Animals/Create.cshtml
@model ESWProjectAlbergue.Models.Animal


@{
    ViewData["Title"] = "Create";
}

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>

<style>
    .container-all {
        background-color: #333333;
        padding: 20px;
        padding-top: 6px;
        border-style: solid;
        border-width: 5px;
        align-content: center;
        align-items: center;
        width: 100%;
        height: 100%;
        margin-top: 5px;
        margin-right: auto;
        margin-left: auto;
        box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
        display: inline-block;
        background-color: #333333;
        border-radius: 25px;
        position: center;
    }

    .whitetext {
        color: white;
        font-family: 'Quicksand', sans-serif;
        font-size: 16px;
    }

    .registar-animal {
        font-family: "Pacifico";
        font-size: 40px;
        width: 100%;
        text-align: center;
        margin-top: 3%;
        color: #FFFFFF;
    }

    .form-create {
    }

    .creates {
        margin: 0 auto;
        width: fit-content;
    }
</style>


<div class="container-all">
    <h2 class="registar-animal">Registar novo animal</h2>



    <div class="form-create">


        <div class="creates">
            <form asp-action="Create" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label whitetext"></label>
                    <input asp-for="Name" class="form-control " style="font-size:13pt;width:300px;" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AnimalType" class="control-label whitetext"></label>

                    <select asp-for="AnimalType" class="form-control" style="font-size:13pt;width:300px;" asp-items="@Html.GetEnumSelectList<EnumAnimalType>()"></select>
                    <span asp-validation-for="AnimalType" class="text-danger"></span>
                </div>


                <div class="form-group">
                    <label asp-for="Gender" class="control-label whitetext"></label>
                    <select asp-for="Gender" class="form-control" style="font-size:13pt;width:300px;" asp-items="@Html.GetEnumSelectList<EnumGenderType>()"></select>
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BirthDate" class="control-label whitetext"></label>
                    <input asp-for="BirthDate" class="form-control" style="font-size:13pt;width:300px;" />
                    <span asp-validation-for="BirthDate" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BreedId" class="control-label whitetext"></label>
                    <select asp-for="BreedId" class="form-control" style="font-size:13pt;width:300px;" asp-items="ViewBag.BreedId"></select>
                    <a href="../AnimalBreeds/Create" class="elements"><span>Adicionar Raça</span></a>
                    <a href="../AnimalBreeds/Index" class="elements"><span>Editar Raças</span></a>
                </div>
                <div class="form-group">
                    <label asp-for="SizeType" class="control-label whitetext"></label>
                    <select asp-for="SizeType" class="form-control" style="font-size:13pt;width:300px;" asp-items="@Html.GetEnumSelectList<EnumSize>()"></select>
                    <span asp-validation-for="SizeType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FurType" class="control-label whitetext"></label>
                    <select asp-for="FurType" class="form-control " style="font-size:13pt;width:300px;" asp-items="@Html.GetEnumSelectList<EnumFurType>()"></select>
                    <span asp-validation-for="FurType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="AgeType" class="control-label whitetext"></label>
                    <select asp-for="AgeType" class="form-control" style="font-size:13pt;width:300px;" asp-items="@Html.GetEnumSelectList<EnumAgeType>()"></select>
                    <span asp-validation-for="AgeType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="BehaviorType" class="control-label whitetext"></label>
                    <select asp-for="BehaviorType" class="form-control" style="font-size:13pt;width:300px;" asp-items="@Html.GetEnumSelectList<EnumBehaviorType>()"></select>
                    <span asp-validation-for="BehaviorType" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label whitetext"></label>
                    <input asp-for="Description" class="form-control" style="font-size:13pt;width:300px;" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Photo" class="control-label whitetext"></label>
                    <input asp-for="Photo" type="file" accept=".png,.jpg,.jpeg,.gif,.tif" />
                    <span asp-validation-for="Photo" class="text-danger"></span>
                </div>




                <div class="form-group">

                    <input type="submit" value="Criar" class="btn btn-default" onclick="return Confirmmessage()" />

                    <a asp-action="Index">Voltar</a>

                </div>
            </form>
        </div>
    </div>



</div>

@Html.Raw(TempData["Success"])
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script>
    function Confirmmessage() {
        var alert = confirm("Tem a certeza que quer registar o animal?");
        if (alert) {
            return true;
        } else {
            return false;
        }
    }
</script>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

ESWProjectAlbergue/Views/Animals/FiltrarNome.cshtml
@model IEnumerable<ESWProjectAlbergue.Models.Animal>

@{
    ViewData["Title"] = "Index";
    var imgsrc = "";

}

<!DOCTYPE html>

<head>
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">

    <style>
        .animalscontainer {
            display: inline;
            width: auto;
            display: inline;
        }

        .animalcontainer {
            position: relative;
            width: auto;
            display: inline-block;
        }

        .animalimage {
            opacity: 1;
            display: block;
            width: 200px;
            height: 200px;
            transition: .5s ease;
            backface-visibility: hidden;
        }

        .middle {
            transition: .5s ease;
            opacity: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            -ms-transform: translate(-50%, -50%)
        }

        .animalcontainer:hover .animalimage {
            opacity: 0.3;
        }

        .animalcontainer:hover .middle {
            opacity: 1;
        }

        .animalnamefemale {
            background-color: hotpink;
            color: white;
            font-size: 16px;
            padding: 16px 32px;
            border-radius: 100px;
            border-style: solid;
            border-width: 2px;
        }

        .animalnamemale {
            background-color: #02A69E;
            color: white;
            font-size: 16px;
            padding: 16px 32px;
            border-radius: 100px;
            border-style: solid;
            border-width: 2px;
        }

        .animalname {
            color: white;
            text-transform: uppercase;
        }



        a {
            color: black;
        }

        .editdelete {
            width: 200px;
        }

        .allanimals {
            background-color: #333333;
            padding: 20px;
            padding-top: 6px;
            border-style: solid;
            border-width: 5px;
            align-content: center;
            align-items: center;
            width: 100%;
            height: 100%;
            margin-top: 5px;
            margin-right: auto;
            margin-left: auto;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            display: inline-block;
            background-color: #333333;
            border-radius: 25px;
            position: center;
        }

        .Animais {
            font-family: "Pacifico";
            font-size: 40px;
            width: 100%;
            text-align: center;
            margin-top: 3%;
            color: #FFFFFF;
        }

        .whitetext {
            color: white;
            font-family: 'Open Sans', sans-serif;
        }

        .button1 {
            background-color: #02A69E;
            text-transform: uppercase;
            border: none;
            color: white;
            padding: 10px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 12px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 3px;
        }

            .button1:hover {
                background-color: gray;
                color: white;
            }

        .button2 {
            background-color: #02A69E;
            text-transform: uppercase;
            border: none;
            color: white;
            padding: 5px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 12px;
            margin: 4px 2px;
            margin-right: 20px;
            cursor: pointer;
            border-radius: 3px;
        }

            .button2:hover {
                background-color: gray;
                color: white;
            }

        .filteranimals {
            display: table;
            margin: 0 auto;
        }

        .filteranimalschildren {
            display: inline;
        }

        .centerdiv {
            display: table;
            margin: 0 auto;
        }

        .centerimage {
            display: block;
            margin-left: auto;
            margin-right: auto;
        }

        .centertext {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="allanimals">
        <h2 class="Animais">Animais</h2>
        <br>
        @if (User.IsInRole("admins") || User.IsInRole("funcionarios"))
        {
            <div class="centerdiv">
                <p class="whitetext button1 centertext">
                    <a asp-action="Create" class="whitetext">Registar Novo Animal</a>
                </p>
            </div>
            <br>
        }
        <div class="filteranimals centerdiv">
            <form asp-controller="Animals" asp-action="FiltrarNumero" method="post" class="whitetext filteranimalschildren">
                <p class="whitetext filteranimalschildren">
                    ID: <input type="number" name="id">
                    <input type="submit" class="button2" value="Filtrar" />
                </p>
            </form>
            <form asp-controller="Animals" asp-action="FiltrarNome" method="post" class="whitetext filteranimalschildren">
                <p class="whitetext filteranimalschildren">
                    Nome: <input type="text" name="name">
                    <input type="submit" class="button2" value="Filtrar" />
                </p>
            </form>
        </div>


        <br>
        <div class="animalscontainer">
            @foreach (var item in Model)
            {

                @if (item.Photo == null)
                {
                    if (item.AnimalType == EnumAnimalType.CAT)
                    {
                        imgsrc = "~/images/caticon.png";
                    }
                    if (item.AnimalType == EnumAnimalType.DOG)
                    {
                        imgsrc = "~/images/dogicon.png";
                    }
                    if (item.AnimalType == EnumAnimalType.OTHER)
                    {
                        imgsrc = "~/images/interrogacao.png";
                    }

                }
                else
                {
                    var base64 = Convert.ToBase64String(item.Photo);
                    imgsrc = string.Format("data:image/gif;base64,{0}", base64);
                }


                @if (item.Gender == EnumGenderType.FEMALE)
                {
                    <div class="animalcontainer">
                        <img src='@imgsrc' class="animalimage" width="200" height="200" style="border-radius:100px; border-style: solid; border-width: 5px; border-color: hotpink;" />
                        <div class="middle">
                            <div class="animalnamefemale">
                                @if (item.AnimalType == EnumAnimalType.CAT)
                                {
                                    <img src='~/images/cat.png' width="40" height="40" class="centerimage">

                                }
                                else
                                {
                                    <img src='~/images/dog.png' class="centerimage">
                                }

                                <a asp-action="Details" asp-route-id="@item.Id" class="animalname centertext">@Html.DisplayFor(model => item.Name)</a>
                            </div>
                        </div>
                    </div>

                }
                @if (item.Gender == EnumGenderType.MALE)
                {
                    <div class="animalcontainer">
                        <img src='@imgsrc' class="animalimage" width="200px" height="200px" style="border-radius:100px; border-style: solid; border-width: 5px; border-color: #02A69E;" />
                        <div class="middle">
                            <div class="animalnamemale">
                                @if (item.AnimalType == EnumAnimalType.CAT)
                                {
                                    <img src='~/images/cat.png' width="40" height="40" class="centerimage">

                                }
                                else
                                {
                                    <img src='~/images/dog.png' class="centerimage">
                                }
                                <a asp-action="Details" asp-route-id="@item.Id" class="animalname">@Html.DisplayFor(model => item.Name)</a>
                            </div>
                        </div>
                    </div>
                }

                <a class="editdelete">



                    @*<a asp-action="Details" asp-route-id="@item.Id">Detalhes</a>*@
                    @if (User.IsInRole("admins") || User.IsInRole("funcionarios"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id" class="whitetext"> Editar</a>
                    }
                    @if (User.IsInRole("admins"))
                    {
                        <a asp-action="Delete" asp-route-id="@item.Id" class="whitetext"> | Eliminar</a>
                    }

                </a>

            }
        </div>
    </div>

</body>